### PR TITLE
Refactor java to kotlin, add showInAppMessageAndroid

### PR DESCRIPTION
**Pull request by offline-first**
-Refactor java to kotlin
-Improve android implementation 
-Update Billing library to 4.1.0
-Add support for in app messages on android (Play Store)

Please turn codecov off for this PR

### CODE REVIEW

**Comment by soarescaique** [comment]
This PR seems to fix Issue #363 . Got no errors testing.

**Comment by hyochan** [comment]
Thanks for reviewing this. Since these are big changes I hope more people to spend time on this `PR` so that we can prevent critical regressions 🙏

**Comment by offline-first** [comment]
I use this Version since one week in production without any issues! The next commits are smaller :)

**Comment by soarescaique** [comment]
I have reviewed the changes this week, and they are looking good! Just waiting for the merge to launch it to production

**Review by hyochan — APPROVED** [review]
I've not actually reviewed this yet.
However, there are people who want this `PR` to be merged so I'll give a try.

Hope it is safe.

Thanks again for the great work 🙏

**Pull request merged**
