### PR TITLE
iOS Promotional Offers Fix

### PR DESCRIPTION
**Pull request by mgonzalezc**
- Fix typo in method call
- Retrieving discounts information

### CODE REVIEW

**Review by hyochan — APPROVED** [review]
Looks like a great improvement. Could you also look at the readme if there are any changes needed?

**Comment by JulianBissekkou** [comment]
I am using this API and I am getting an error saying that the user is not eligible for this offer.
Can you maybe help me with this?

```dart
  @override
  Future<void> subscribeToProduct(String productId, String offerId) => withPackage((iap) async {
        final userId = getUserId();

        final offerSignature = await _requestOfferSignature(
          productId: productId,
          offerId: offerId,
          username: userId,
        );

        final completer = Completer<void>();
        FlutterInappPurchase.purchaseUpdated.listen((event) {
          print(event);
          //TODO Finish transaction
          completer.complete();
        });

        // ignore: unawaited_futures
        iap.requestProductWithOfferIOS(productId, userId, <String, Object>{
          "identifier": offerId,
          "keyIdentifier": offerSignature.keyIdentifier,
          "nonce": offerSignature.nonce,
          "signature": offerSignature.signature,
          "timestamp": offerSignature.timestamp,
        });

        return completer.future;
      });
```

**Comment by JulianBissekkou** [comment]
Especially @mgonzalezc since you are using this feature 👍

**Comment by mgonzalezc** [comment]
Hello @JulianBissekkou!

On the one hand, the iOS promotional offers can only be purchased if the user signed up for the same subscription you are creating the signature for. For example, if you have a subscription with id julian.awesome.game, and you have created a promotional offer inside, you can only purchase the offer if you had a subscription to julian.awesome.game in the past. 

You can determine the eligibility of your user in your server. For this matter, you can implement App Store Server Notifications and save if the user is eligible in your database when you detect cancelling, for example.

On the other hand, I have experienced some issues when the purchase was done a long time ago before Apple implemented promotional offers. The error thrown was the same you describe. But this has not happened to me with more recent subscriptions.

By last, is it possible that your signature is not correct?

**Comment by JulianBissekkou** [comment]
@mgonzalezc Thanks for the quick answer!

> you can only purchase the offer if you had a subscription to julian.awesome.game in the past.
I am not sure if I understood this correctly. Are you saying that I have to create a subscription first and after that, I can apply the offer to it? 🤔 
In my case, the user will have a trial period of 1 month or 7 days. The user has no subscriptions when I call the method. 
`productId` is the id of the subscription and `offerId` is the Id of the offer which was inside of `discountIOS`. 


>You can determine the eligibility of your user in your server. For this matter, you can implement App Store Server Notifications and save if the user is eligible in your database when you detect cancelling, for example.

I didn't use the App Store Server Notification yet because it seems that I am doing something wrong. Every user should be eligible for my offer or am I missing something? 🤔 


>By last, is it possible that your signature is not correct?
It looks correct when I compare the format of the example signature in the docs and there is no error that tells me that the signature is wrong. I am generating the signature in my kotlin/java backend. Maybe you can share your implementation of the signature creation?

Thanks a lot for helping, really appreciate your answer! ☺️

**Comment by mgonzalezc** [comment]
> I am not sure if I understood this correctly. Are you saying that I have to create a subscription first and after that, I can apply the offer to it? 🤔

Yes, this is how promotional offers work. You can check [this](https://help.apple.com/app-store-connect/#/dev16dfca448)

In short, promotional offers belong to an auto-renewable subscription so if you have three different subscriptions and want to offer a 40% discount in each of them, you will need to add three promotional offers, once per subscription, inside each subscription.

> In my case, the user will have a trial period of 1 month or 7 days. The user has no subscriptions when I call the method.
productId is the id of the subscription and offerId is the Id of the offer which was inside of discountIOS.
Am I doing it wrong this way?

Do you mean you have different [intro prices](https://developer.apple.com/documentation/storekit/in-app_purchase/subscriptions_and_offers/implementing_introductory_offers_in_your_app) configured for your subscription? Or do you have your own trial implementation? 

If you are using intro prices, then your users have a subscription (in intro period, but a subscription either way). However, if you are using your own trial implementation, your users will not be eligible for a promotional offer. For them to be eligible, they need to buy the subscription (or trial) first from App Store. 

> I didn't use the App Store Server Notification yet because it seems that I am doing something wrong. Every user should be eligible for my offer or am I missing something? 🤔

They will only be eligible if they bought the subscription(or trial) before.

> Maybe you can share your implementation of the signature creation?

I am using firebase functions + firebase storage for this matter:

 ```
  const productId = data.productId; //this comes from my app
  const offerId = data.offerId; //this comes from my app
  const username = data.username; //this comes from my app

  const keyId = <key_id>
  const nonce = uuidv4()
  const timestamp = new Date().getTime()
  const bucket = admin.storage().bucket();
  const filename = <path_p8_file>
  const keyFile = await bucket.file(filename).download();

  const payload = <bundle_id> + '\u2063' 
                + keyId + '\u2063' 
                + productId + '\u2063' 
                + offerId + '\u2063' 
                + username + '\u2063' 
                + nonce + '\u2063' 
                + timestamp

  
  const privateKey = keyFile[0].toString('ascii')

  const base64Signature = crypto.createSign('RSA-SHA256')
                          .update(payload)
                          .sign(privateKey, 'base64');

  const response = {
    "identifier": offerId,
    "nonce": nonce, 
    "timestamp": timestamp.toString(), 
    "keyIdentifier": keyId, 
    "signature": base64Signature,
  };

  return response;
```

**Comment by JulianBissekkou** [comment]
@mgonzalezc 
Okay, there was a misunderstanding on my side because I tried to use the promotional offer as trial offers which doesn't work.
Quite a stupid mistake from my side. 🤦 
It works now 👍 

Anyways, thanks for your help and that you took the time to answer all my questions! 👍 
As you saw, I am new to in-app payment, but I am quite experienced with Flutter and if you need help with a flutter related problem I can give back and help you there in the future.

Have a nice weekend!

**Pull request merged**
