### PR TITLE
Migrate to android billing api v3

### PR DESCRIPTION
**Pull request by mk-dev-1**
Google Play Billing Library v3.0 was released in June 2020 and is becoming mandatory next year. This PR addresses the issue.

Reference: https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html

### CODE REVIEW

**Review by hyochan — CHANGES_REQUESTED** [review]
Thanks for the great PR! However, `accoutId` and `developerId` should not be removed and this should be replaced to `obfuscatedAccountIdAndroid` and `obfuscatedProfileIdAndroid` as in dooboolab/react-native-iap/pull/1141.

Could you kindly fix your changes?

**Comment by mk-dev-1** [comment]
Hopefully, this should do it. Would you mind checking?

Btw: Should the changelog be updated with a PR or do you do that upon merging?

**Review by hyochan — CHANGES_REQUESTED** [review]
It is almost complete. Would you mind changing one more thing? Since `purchaseToken` is only for android, I think it'd be better to rename it to `purchaseTokenAndroid` to ensure that it is only needed in android.

**Review by hyochan — APPROVED** [review]
Thanks for your contribution! Great work 💯

**Pull request merged**
