### PR TITLE
Unify PlatformException, cleanup new, VSC settings, DateTime instead of string

### PR DESCRIPTION
**Pull request by lukepighetti**
Unify PlatformException
remove unnecessary "new" keywords
add VSC editor settings, enforcing 80 col and `dartfmt` use
dates are now DateTime instead of dynamic (please confirm types coming in from those functions)

### CODE REVIEW

**Comment by dooboolab** [comment]
@lukepighetti Thanks. Have you tested this in both `android` and `ios`?

**Comment by dooboolab** [comment]
@lukepighetti Also could you do my favor? Could you check the `Readme.md` and update the types you've updated?

**Comment by lukepighetti** [comment]
I will do some testing today as I am working on a project that will make us of this. I will also update the Readme. Will tag when ready.

**Comment by dooboolab** [comment]
@lukepighetti Nope. Usually, I've done it myself. Need to improve this stage currently. Hope you can do smoe testing yourself and when ready, I'll do it after you've done some test and review.

**Comment by lukepighetti** [comment]
Seems to work fine on iOS. Will be testing Android shortly.

**Comment by lukepighetti** [comment]
@dooboolab minor testing in Android (I am only using a few features) and it works. Please let me know what you think.

**Comment by lukepighetti** [comment]
@dooboolab I have a bunch of other changes that are somewhat radical and I think they deserve their own PR. Should I wait until you close this one before opening that one?

**Comment by lukepighetti** [comment]
I added documentation so that you can refer people to Pub for documentation, which is pretty normal for Dart projects. This also means you won't have to update the front page for documentation anymore. 👍

**Comment by lukepighetti** [comment]
Just wanted to confirm that this is all working for me on iOS and Android

**Comment by lukepighetti** [comment]
Thank you for accepting my changes! This is my first real pull request so I am honored.

pub.dartlang.org will automatically generate API docs based on comments, which will also show up in the IDE. It's very handy!

I believe this is from README.md so I would recommend actually removing anything API related from README.md. https://pub.dartlang.org/documentation/flutter_inapp_purchase/latest/

And if you click in through the sidebar you'll see that the inline comments get pulled in along with all the types! This is the most common way for Dart package APIs to be referenced.

https://pub.dartlang.org/documentation/flutter_inapp_purchase/latest/flutter_inapp_purchase/FlutterInappPurchase-class.html

**Comment by dooboolab** [comment]
@lukepighetti Awesome!

**Pull request merged**
